<?php
// Echo Open software Copyright © 2012 KnowledgeWorks Foundation
// ECHO OPEN trademark and logo are trademarks of New Technology Network LLC
// The Echo Open software is licensed under the GNU GPLv2.  For licensing information // please contact New Technology Network Licensing at: // webmaster@newtechnetwork.org or 935 Clinton Street, Napa, CA 94559.


global $base_path;      //Returns the root web folder path

$html_header = '<div style="margin: 7px 0pt 0pt;" class="HomePageFeatures">
<div id="AgendaActivitiesAndNotisfication">
	<div class="TopRightOrangeCorner">
		<div class="TopLeftOrangeCorner">
			<div class="AgendaActivitiesAndNotisfication">
				<div class="AgendaOrangeBoxHeading">
					<h2>Network Features</h2>
				</div>
			</div>
		</div>
	</div>
	<div class="NoticficationMainContent">
		<table cellspacing="0" cellpadding="0" border="0" width="100%">
			<tbody><tr>
                            <td class="MiddleLeftOrangeCorner"></td>
                            <td class="MiddleCenterOrangeCorner">
                            <div class="Feature">';

$html_footer = '            </div>
                            </td>
                            <td class="MiddleRightOrangeCorner"></td>
			</tr>
			<tr>
                            <td class="BottomLeftOrangeCorner"></td>
                            <td class="BottomCenterOrangeCorner"></td>
                            <td class="BottomRightOrangeCorner"></td>
			</tr>
		</tbody></table>
	</div>
</div>
</div>';
// -------------------------
// Featured Block ver 13.0
// -------------------------
$html_custom = '<center><img src="themes/Boldr/Images/flashImg.jpg" alt="Sample Featured Item" width="200" height="150" border="0" />
<font size=3><strong><a href="#" target="_blank">Sample Featured [video]</a></strong></font><br /><br /></center>';
