<?php
$HTMLform_school_setting_bluebox_start = t(<<<END
   <div id="ActivitiesCSS"  style="width:auto">
   <div class="LightBlueBottomRightCorner">
            <div class="LightBlueBottomLeftCorner">
                    <div class="LightBlueTopRightCorner">
                            <div class="LightBlueTopLeftCorner">
                            <div class="ActivitiesAssignment">
                            <table cellpadding="8" class="table" cellspacing="0" border="0" width="100%">


END
);

$HTMLform_school_setting_bluebox_end = t(<<<END
                            </table>
                            </div>
                            </div>
                    </div>
            </div>
    </div>
    </div>
END
);



$HTMLform_course_msgbox1_hdr = t(<<<END
   <div id="BoldrMessageBox">
<table cellspacing="0" style="background-color:#F07D24" cellpadding="0" border="0" align="center" width="100%">
<tbody>
<tr>
    <td class="msgboxTopLeft">
    &nbsp;
    </td>
    <td style="border:none">
    </td>
    <td class="msgboxTopRight">
    &nbsp;
    </td>
</tr>
<tr>
<td style="border:none">
					&nbsp;</td>
<td style="border:none;font-size:16px;font-weight:bold" class="msgboxcenterNoIcon">


END
);

$HTMLform_course_msgbox1_ftr = t(<<<END
</td>
<td style="border:none">
					&nbsp;</td>
</tr>
<tr>
    <td class="msgboxBottomLeft">
    &nbsp;
    </td>
    <td style="border:none">
    </td>
    <td class="msgboxBottomRight">
    &nbsp;
    </td>
</tr>

</tbody>
</table>
</div>
END
);

?>
