<?php
// Echo Open software Copyright © 2012 KnowledgeWorks Foundation
// ECHO OPEN trademark and logo are trademarks of New Technology Network LLC
// The Echo Open software is licensed under the GNU GPLv2.  For licensing information // please contact New Technology Network Licensing at: // webmaster@newtechnetwork.org or 935 Clinton Street, Napa, CA 94559.


$HTMLform_groupbox_announcement_hdr = t(<<<END
<div id="AgendaAnnouncement" style="margin-bottom:10px;">
	<div class="TopRightOrangeCorner">
		<div class="TopLeftOrangeCorner">
			<div class="AnnouncementHeadingMainDiv">
				
				<div class="AgendaOrangeBoxHeading">
					<h2>Announcement</h2>
				</div>
			</div>
		</div>
	</div>
	<div class="AnnouncementMainContent">
		<table cellpadding="0" cellspacing="0" border="0" width="612px">
			<tr>
				<td class="MiddleLeftOrangeCorner">&nbsp;</td>
				<td class="MiddleCenterOrangeCorner">
					
				 

END
);

// End Of Field Set
$HTMLform_groupbox_announcement_ftr = t(<<<END

   </td>
				<td class="MiddleRightOrangeCorner">&nbsp;</td>
			</tr>
			<tr>
				<td class="BottomLeftOrangeCorner">&nbsp;</td>
				<td class="BottomCenterOrangeCorner">&nbsp;</td>
				<td class="BottomRightOrangeCorner">&nbsp;</td>
			</tr>


                         </table>
	</div>
</div>

END
);
