<?php
// Echo Open software Copyright © 2012 KnowledgeWorks Foundation
// ECHO OPEN trademark and logo are trademarks of New Technology Network LLC
// The Echo Open software is licensed under the GNU GPLv2.  For licensing information // please contact New Technology Network Licensing at: // webmaster@newtechnetwork.org or 935 Clinton Street, Napa, CA 94559.


// $Id: ntlpprojectactivity.module,v 1.1.4.7 2009/04/21 08:51:21 jaydub Exp $

/**
 * Activity definition file
 *
 * This defines what hooks activity module should use
 */
function ntlpprojectactivity_activity_info() {
  return array(
    'ops' => array( 'archive' => t('Archive Request'),
                    'exemplary' => t('Exemplary')),
    'types' => array(
      'projectaction' => t('Project Action'),
    ),
    'roles' => array(
      'user' => array(
        '#name' => t('Author'),
        '#description' => t('The person who made the project action.'),
        '#default' => array(
            'archive' => 'Project Archive Request Submitted: [ntlp-node-title]',
            'exemplary' => 'Project Awarded Exemplary Status: [ntlp-node-title]',
        ),
      ),
      // This is what corresponds to ACTIVITY_ALL
      'all' => array(
        '#name' => t('All'),
        '#description' => t('The general public.'),
        '#default' => array(
            'archive' => 'Project Archive Request Submitted: [ntlp-node-title]',
            'exemplary' => 'Project Awarded Exemplary Status: [ntlp-node-title]',
        ),
      ),
    ),
  );
}

/**
 * Token module integration. Defines available default tokens.
 */
function ntlpprojectactivity_token_list($type = 'all') {

    if ($type == 'ntlpprojectactivity') {
        $tokens['ntlpprojectactivity'] = array(
          'node-id' 	=> t('Id of the post'),
          'node-title' 	=> t('Title of the post'),
          'node-link' 	=> t('Link to the post'),
          'node-type' 	=> t('The node type of the post'),
        );
        return $tokens;
    }
}

/**
 * Token module integration. Defines available default token values.
 */
function ntlpprojectactivity_token_values($type, $data = NULL, $options = array()) {

//    if ($type == 'ntlpprojectactivity' && !empty($data)) {
//        $data['node-type'] = theme('activity_node_type', $data['node-type']);
//        $data['node-link'] = l($data['node-title'], 'node/'. $data['node-id'], $link_class);
//        return $data;
//    }
}

/**
 * Implementation of hook_og().
 */
function ntlpprojectactivity_submit($op, $project_id, $target_uid, $uid) {

    switch ($op) {
    case 'archive':
    case 'exemplary':

      $node = node_load($project_id);
      $type = 'projectaction';
      
      // Check if both type and operation are
      // enabled for activity. If not then stop here
      if (!in_array($type, variable_get('ntlpprojectactivity_token_types', array($type)), TRUE) ||
        !in_array($op, variable_get('ntlpprojectactivity_op_types', array($op)), TRUE)) {
        return FALSE;
      }

      // Privacy setting check
      $user = user_load(array('uid' => $uid));
      if (activity_user_privacy_optout($user)) {
        return FALSE;
      }

      // User hide activity permission check
      if (user_access('hide activity', $user)) {
        return FALSE;
      }

      $data = array(
        'operation' 	=> $op,
        'node-id'       => $node->nid,
        'node-title' 	=> $node->title,
        'node-type' 	=> $node->type,
        'node-context'  => $target_uid,
      );

      $target_users_roles = array(
          ACTIVITY_ALL => 'all',
          $node->uid => 'author'
        );
      //$target_users_roles[$graded_user] = ($graded_user == -1 ? 'all' : 'user');

      activity_insert($user->uid, 'ntlpprojectactivity', $type, $op, $data, $target_users_roles);
      break;
  }
}

/**
 * Implementation of hook_menu().
 */
function ntlpprojectactivity_menu() {
  $items = array();

  $items['activity/og'] = array(
    'title' => 'My groups activity',
    'page callback' => 'ntlpprojectactivity_page',
    'type' => MENU_LOCAL_TASK,
    'access callback' => 'user_access',
    'access arguments' => array('view own activity'),
  );
    
  return $items;
}


