<?php
// Echo Open software Copyright © 2012 KnowledgeWorks Foundation
// ECHO OPEN trademark and logo are trademarks of New Technology Network LLC
// The Echo Open software is licensed under the GNU GPLv2.  For licensing information // please contact New Technology Network Licensing at: // webmaster@newtechnetwork.org or 935 Clinton Street, Napa, CA 94559.


module_load_include('inc', 'ntlp_school', 'data_access');
module_load_include('inc', 'ntlp_school', 'ui_tools');
module_load_include('inc', 'ntlp_grade', 'grade_content');
module_load_include('inc', 'ntlp_grade', 'data_access');
include 'student_snapshot_page.inc';
include 'grade_header.content.inc';
include 'pagination/pagination2.php';

function ntlp_grade_menu() {

    $items['ntlp/grades/student_snapshot/%'] = array(
            'title' => t('Student Snapshot'),
            'page callback' => 'student_snapshot_frm',
            'page arguments' => array(3),        //Course id, Enroll-in-role_id and Comma delimited user ids
            'access arguments' => array('view student snapshot'),
            'type' => MENU_CALLBACK,
    );

    $items['ntlp/grades/student_snapshot/outcome/%/%'] = array(
            'title' => t('Student Snapshot'),
            'page callback' => '_get_user_school_outcome_pg',
            'page arguments' => array(4, 5),
            'access arguments' => array('view student snapshot'),
            'type' => MENU_CALLBACK,
    );

    $items['ntlp/grade/student/filter'] = array(
            'title' => t('Grades Student Filter'),
            'page callback' => 'ntlp_grade_student_filter',
            'access arguments' => array('view student snapshot'),
            'type' => MENU_CALLBACK,
    );

    $items['ntlp/blocks/get_school_terms_combo/%'] = array(
            'title' => t('Get school term by its id.'),
            'page callback' => 'get_school_terms_combo',
            'page arguments' => array(3),
            'access arguments' => array('create ntlp_course content'),
            'type' => MENU_CALLBACK
    );

    $items['ntlp/change/school/term/%'] = array(
            'page callback' => 'change_school_term',
            'page arguments' => array(4),
            'access arguments' => array('access content'),
            'type' => MENU_CALLBACK,
    );
    $items['ntlp/change/course/term/%'] = array(
            'page callback' => 'change_course_term',
            'page arguments' => array(4),
            'access arguments' => array('access content'),
            'type' => MENU_CALLBACK,
    );
    
    return $items;
}


function change_school_term($term_tid) {
    $term_tid = (int) $term_tid;
    $_SESSION['CURRENT_SCHOOL_TERM'] = $term_tid;
}
function change_course_term($term_tid) {
    $term_tid = (int) $term_tid;
    $_SESSION['CURRENT_COURSE_TERM'] = $term_tid;
}

//For all defined content types, we should use its auto generated contenttype specific permissions
function ntlp_grade_perm() {
    return array('view grades' , 'edit grades', 'view student snapshot');
}


function ntlp_grade_block($op = 'list', $delta = 0, $edit = array()) {
    // The $op parameter determines what piece of information is being requested.
    switch ($op) {
        case 'list':
        // If $op is "list", we just need to return a list of block descriptions.
        // This is used to provide a list of possible blocks to the administrator,
        // end users will not see these descriptions.
            $blocks[0] = array(
                    'info'       => t('NTLP: My Courses Grade Book'),
            );
            $blocks[1] = array(
                    'info'       => t('NTLP: Grade Student'),
            );
            $blocks[2] = array(
                    'info'       => t('NTLP: Student Reports'),
            );
            $blocks[3] = array(
                    'info'       => t('NTLP: Grade Tabs'),
            );

            return $blocks;
        case 'configure':
        // If $op is "configure", we need to provide the administrator with a
        // configuration form. The $delta parameter tells us which block is being
        // configured. In this example, we'll allow the administrator to customize
        // the text of the first block.
            $form = array();
            /*      if ($delta == 0) {
        // All we need to provide is a text field, Drupal will take care of
        // the other block configuration options and the save button.
        $form['ntlp_blocks_string'] = array(
          '#type' => 'textfield',
          '#title' => t('Block contents'),
          '#size' => 60,
          '#description' => t('This string will appear in the example block.'),
          '#default_value' => variable_get('block_example_string',  t('Some example content.')),
        );
      }*/
            return $form;
        case 'save':
        /*      // If $op is "save", we need to save settings from the configuration form.
      // Since the first block is the only one that allows configuration, we
      // need to check $delta to make sure we only save it.
      if ($delta == 0) {
        // Have Drupal save the string to the database.
        variable_set('block_example_string', $edit['block_example_string']);
      }
      return;*/
        case 'view': default:
        // If $op is "view", then we need to generate the block for display
        // purposes. The $delta parameter tells us which block is being requested.

            switch ($delta) {
                case 0:
                // The subject is displayed at the top of the block. Note that it
                // should be passed through t() for translation.
                    $block['subject'] = t('NTLP: My Courses Grade Book');
                    $block['content'] = mycourses_gradebook_contents();
                    break;
                case 1:
                    $block['subject'] = t('NTLP: Grade Students');
                    $block['content'] = grade_students();
                    break;
                case 2:
                    $block['subject'] = t('NTLP: Grade Student Reports');
                    $block['content'] = '';
                    break;
                case 3:
                    $block['subject'] = t('NTLP: Grade Tabs');
                    $block['content'] = ntlp_grade_tabs();
                    break;

            }
    }
    return $block;

}
?>
